module ccReg {

  /// Typ pro status flag domény v whoisu
  enum WhoisDomainStatus  { WHOIS_ACTIVE, WHOIS_EXPIRED };

  /// Typ pro data o doméně
  struct DomainWhois
  {
    WhoisDomainStatus status; ///< Stav domény
    string created; ///< Datum vytvoření domény
    string expired; ///< Datum expirace domény
    string registrarName; ///< Jméno registrátora
    string registrarUrl; ///< Webová adresa registrátora
    NameServers ns; ///< Seznam nameserverů
    TechContact tech; ///< Seznam idenitifikátorů technických kontaktů
  };

  /// Rozhraní pro WHOIS
  interface Whois
  {
    /// Vyjímka pro případ chyby
    exception WhoisError {
      string message; ///< Popis chyby
    };
    /// Vyjímka v případě nenalezení zadané domény
    exception DomainNotFound {
      string timestamp; ///< I když doména neexistuje potřebujeme timestamp
    };

    /// Vraci údaje o doméně pro whois podle názvu
    /** 
     \param domain_name Název požadované domény
     \param timestamp Vrací čas vyřízení požadavku
     \return
    */
    DomainWhois getDomain(
      in string domain_name,
      out string timestamp
    ) raises (WhoisError, DomainNotFound);
  };
};
