module ccReg {

  /// Struktura pro načítání parametrů zóny
  struct Zone
  {
   long id; 
   string  fqdn; ///< Název zóny (např. cz)
   short ex_period_min; ///< Minimální perioda pro prodloužení
   short ex_period_max; ///< parametry zony
   short val_period; ///< parametry zony
   short dots_max; ///< parametry zony
   boolean enum_zone; ///< parametry zony
  };
  /// Seznam zón
  typedef sequence < Zone > Zones;

};
