// IDL rozhrani pro volani CORBA funkci
// interfaces: EPP , Whois , Admin

module ccReg
{
typedef unsigned long long timestamp;

// typy funkci pro transfer
enum TransferFunc{ Approve , Cancel , Query , Reject , Request } ;
enum StatusToken { OK , Linked , 
                  clientDeleteProhibited ,
                  clientUpdateProhibited,
                  pendingCreate, 
                  pendingDelete,
                  pendingTransfer,
                  serverDeleteProhibited,
                  serverUpdateProhibited };

// vracena struktura 

struct Response{
short errCode; // chybove hlaseni
string svTRID; // server transaction ID
};


typedef  sequence<string> NameServers;
typedef  sequence<string> InetAddress;
typedef  sequence<string> TechContact;
typedef  sequence<string> AdminContact;
typedef  sequence<string> Check; // sequence pro check
typedef  sequence<short> Avail; // jednicka ci nula 

// typedef  sequence<short> Status; // musel jsem predelat na short
typedef short Status;

struct DNSHost_str{
string fqdn; // fqdn DNS serveru
InetAddress inet; // pole ip adres 
};

typedef sequence<DNSHost_str> DNSHost;

struct Contact{
string ROID;    // identifikator kontaktu  repository ID
string ClID;    // identifikator registratora ktery ma pravo na zmeny
string CrID;    // identifikator registratora ktery vytvoril kontak
string UpID;    // identifikator registratora ktery provedl zmeny
Status stat; // status sequence
timestamp CrDate; // datum a cas vytvoreni
timestamp UpDate; // datum a cas zmeny
timestamp TrDate;  // datum a cas transferu
string Name; // jmeno nebo nazev kontaktu
string Organization; // nazev organizace
string Street1; // adresa
string Street2; // adresa
string Street3; // adresa
string City;  // obec
string StateOrProvince;
string PostalCode; // PSC
string Country; // kod zeme ISO dve pismena velke
string Telephone;
string Fax;
string Email;
string NotifyEmail; // upozornovaci email
string VAT; // DIC 
string SSN; // SSN
string AuthInfoPw ; // autentifikace
boolean DiscloseName; // povolovani zobrazeni
boolean DiscloseOrganization;
boolean DiscloseAddress;
boolean DiscloseTelephone;
boolean DiscloseFax;
boolean DiscloseEmail;
};

// struktura pro popis hostu
struct Host{
string fqdn; // fqdn nazev hostu 
string nsset; // handle na nsset
Status stat; // status sequence
timestamp CrDate; // datum vytvoreni
timestamp UpDate; // datum zmeny
string ClID;    // identifikator registratora ktery vytvoril host
string UpID;    // identifikator registratora ktery zmenil zaznam
InetAddress inet; // sequence ip adres
};

struct NSSet{
string ROID;
string handle;
Status stat; // status sequence
string ClID;    // identifikator registratora ktery ma pravo na zemnu
string CrID;    // identifikator registratora ktery zaznam vytvoril
string UpID;    // identifikator registratora ktery zmenil zaznam
timestamp CrDate; // datum a cas vytvoreni
timestamp ExDate; // taum a cas expirace domeny
timestamp UpDate;  // datum a cas update
string AuthInfoPw ; // autentifikace
DNSHost dns; // hosty DNS
TechContact tech; // sequence handle na technicke kontakty
};

// struktura pro popis domen
struct Domain{
string ROID; 
string name; // fqdn nazev domeny
string Registrant; // ROID registranta contactu
string nsset; // handle NSSETu
Status stat; // status sequence
string ClID;    // identifikator registratora ktery ma pravo na zemnu
string CrID;    // identifikator registratora ktery zaznam vytvoril 
string UpID;    // identifikator registratora ktery zmenil zaznam
timestamp CrDate; // datum a cas vytvoreni
timestamp ExDate; // taum a cas expirace domeny
timestamp TrDate;  // datum a cas transferu
string AuthInfoPw ; // autentifikace
AdminContact admin; // administrativni kontakty (handle)
};

// pro klienty EPP  protokolu 
interface EPP{

   // pro vraceni serverTRID 
   Response GetTransaction(  in long clientID ,  in string clTRID , in short errCode );

   // pro prihlaseni clienta 
   Response  ClientLogin(in string ClID , in string passwd , in string newpass ,  in string clTRID  ,  out long clientID  );
   Response  ClientLogout(in long clientID  , in string clTRID );

   // zjisteni kontaktaktu
   Response  ContactCheck( in  Check handle  , out Avail a , in long clientID , in string clTRID );
   // info o kontaktni osobe
   Response  ContactInfo(  in  string  handle  , out Contact c , in long clientID , in string clTRID );
   // vymazani kontaktni osoby 
   Response  ContactDelete( in  string handle  , in long  clientID , in string clTRID );
   // zmena udaju u kontaktni osoby 
   Response  ContactUpdate( in  string handle  , in Contact c , in long clientID , in string clTRID  );  
   // vytvoreni kontaktni osoby 
   Response  ContactCreate( in  string handle  ,  in Contact c  , in long clientID , in string clTRID );
   // Funkce pro transfer kontaktu typ funkce nezadana


   // check hostu
   Response  HostCheck( in Check name  ,  out Avail a ,  in long clientID , in string clTRID );
   // info o hostu
   Response  HostInfo( in string name , out Host h, in long clientID , in string clTRID  );
   // smazani hostu
   Response  HostDelete( in string name , in long clientID , in string clTRID );
   // vytvoreni hostu
   Response  HostCreate( in string name , in Host h , in long clientID , in string clTRID );
   // zmena udaju update
   Response  HostUpdate( in string name , in Host h , in long clientID , in string clTRID );


// predelano na NSSET
   // check hostu
   Response  NSSetCheck( in Check handle  ,  out Avail a ,  in long clientID , in string clTRID );
   // info o hostu
   Response  NSSetInfo( in string handle , out NSSet n, in long clientID , in string clTRID  );
   // smazani hostu
   Response  NSSetDelete( in string handle , in long clientID , in string clTRID );
   // vytvoreni hostu
   Response  NSSetCreate( in string handle , in NSSet n , in long clientID , in string clTRID );
   // zmena udaju update
   Response  NSSetUpdate( in string handle , in NSSet n , in long clientID , in string clTRID );


//  funkce na spravu domen
   Response  DomainCheck( in Check fqdn  ,  out Avail a , in long clientID , in string clTRID );
   Response  DomainInfo( in string fqdn , out Domain d , in long clientID , in string clTRID );
   Response  DomainDelete( in string fqdn , in long clientID , in string clTRID );
   Response  DomainUpdate( in string fqdn , in Domain d , in long clientID , in string clTRID );
   Response  DomainCreate( in string fqdn , in Domain d , in long clientID , in string clTRID );
   // doba prodlouzeni period je v mesicich
   Response  DomainRenew( in string fqdn , in Domain d , in short period , in long clientID ,  in string clTRID );
//  transfer zatim nezadan  Response  DomainTransfer(



};

// struktura
struct DomainWhois{
string name;
// string description; // popis domeny ted tam je 
short status; // status 1 REGISTRED - 0 FREE
timestamp created;
timestamp expired;
string registrarName;  // jmeno registratora
string registrarUrl; // odkaz na jeho webovou adresu
NameServers ns; // sequence nameservru
string nsset; // handle NSSETu
TechContact tech; // sequence handle na technicke kontakty
AdminContact admin; // administrativni kontakty (handle)
};

interface Whois{
    // vraci identifikaci domeny pro whois server podle nazvu
    DomainWhois Domain( in string  domain_name );
};


// administratorske rozhrani
interface Admin{

};

};
