module ccReg {

	interface Logger {
		TID CreateRequest(in string sourceIP, in RequestServiceType serv, in string content_in, in RequestProperties props, in RequestActionType action_type, in TID session_id);
                boolean UpdateRequest(in TID id, in RequestProperties props);
                boolean CloseRequest(in TID id, in string content_out, in RequestProperties props);
                boolean CloseRequestLogin(in TID id, in string content_out, in RequestProperties props, in TID session_id);
		TID CreateSession (in Languages lang, in string name);	
		boolean CloseSession (in TID id);
		RequestActionList GetServiceActions(in RequestServiceType serv);
        RequestServiceList GetServices();

// methods which allow to run logd on separate database/host
                Registry::PageTable createPageTable(in string session_id);
                void deletePageTable(in string session_id);

                Registry::Request::Detail getDetail(in TID id) raises (ccReg::Admin::ObjectNotFound);
	};
};

