#ifndef PAIN_IDL_DB189D57EF894375BECB3931E4AD4E54
#define PAIN_IDL_DB189D57EF894375BECB3931E4AD4E54

#include "IsoDateTime.idl"

module Registry {
module Accounting {

exception OBJECT_NOT_FOUND {};
exception INVALID_CREDIT_VALUE {};
exception DUPLICATE_IDENT_ALREADY_EXISTS {};
exception INTERNAL_SERVER_ERROR {};

typedef string Money;

interface AccountingIntf
{

    void increase_credit_of_registrar(
            in string ident,
            in string registrar_handle,
            in Money credit_value)
    raises (OBJECT_NOT_FOUND, INVALID_CREDIT_VALUE, DUPLICATE_IDENT_ALREADY_EXISTS, INTERNAL_SERVER_ERROR);

    void decrease_credit_of_registrar(
            in string ident,
            in string registrar_handle,
            in Money credit_value)
    raises (OBJECT_NOT_FOUND, INVALID_CREDIT_VALUE, DUPLICATE_IDENT_ALREADY_EXISTS, INTERNAL_SERVER_ERROR);

};

}; // Registry::Accounting
}; // Registry

#endif
