#ifndef ADMINISTRATIVE_BLOCKING_IDL_
#define ADMINISTRATIVE_BLOCKING_IDL_

module Registry {
module Administrative {

struct StatusDesc
{
    short id;
    string shortName;
    string name;
};

typedef sequence<StatusDesc> StatusDescList;
/*
   serverRenewProhibited
   serverOutzoneManual
   serverInzoneManual
   serverRegistrantChangeProhibited
   serverDeleteProhibited
   serverTransferProhibited
   serverUpdateProhibited
*/

typedef sequence<string> DomainList;
typedef sequence<string> StatusList; /* shortName */

struct Date {
    short day;
    short month;
    short year;
};

valuetype NullableString string;
valuetype NullableBoolean boolean;
valuetype NullableDate Date;

exception ALREADY_BLOCKED
{
    DomainList what;
};

exception INTERNAL_SERVER_ERROR
{
    string what;
};

  ///Blocking interface
  interface Blocking
  {
    string getName(in string lang)
        raises (INTERNAL_SERVER_ERROR);
    unsigned long long getLangID(in string lang)
        raises (INTERNAL_SERVER_ERROR);

    StatusDescList getBlockingStatusDescList(in string lang)
        raises (INTERNAL_SERVER_ERROR);

    void blockDomains(
        in DomainList domain_list,
        in StatusList status_list,
        in boolean block_owner,
        in boolean create_owner_copy)
        raises (INTERNAL_SERVER_ERROR, ALREADY_BLOCKED);

    void updateBlockDomains(
        in DomainList domain_list,
        in StatusList status_list);

    void restorePreAdministrativeBlockStates(in DomainList domain_list)
        raises (INTERNAL_SERVER_ERROR);

    void unblockDomains(
        in DomainList domain_list,
        in NullableString new_owner,
        in boolean remove_admin_c)
        raises (INTERNAL_SERVER_ERROR);

    void blacklistAndDeleteDomains(
        in DomainList domain_list,
        in NullableDate blacklist_to_date)
        raises (INTERNAL_SERVER_ERROR);

    void blacklistDomains(
        in DomainList domain_list,
        in NullableDate blacklist_to_date,
        in boolean with_delete)
        raises (INTERNAL_SERVER_ERROR);

    void unblacklistAndCreateDomains(
        in DomainList domain_list,
        in string owner)
        raises (INTERNAL_SERVER_ERROR);
  };
};
};

#endif
