// IDL interface for CORBA functions
// interfaces: EPP , Whois , Admin
#include "_dataTypes.idl"
#include "_Mailer.idl"
#include "_Admin.idl"
#include "_Registry.idl"
#include "_EPP.idl"
#include "_Whois.idl"
#include "_ZoneGenerator.idl"
#include "_TechCheck.idl"
#include "_FileManager.idl"

// for zone handling
#include "_zone.idl"

