#ifndef LIB_DATETIME_IDL_
#define LIB_DATETIME_IDL_

module ccReg {
  /// Structure for handling day
  struct DateType {
    short day; ///< day of month (1..31)
    short month; ///< month in year (1..12)
    short year; ///< year (i.e. 2006)
  };
  
  /// Structure for handling date and time
  struct DateTimeType {
    DateType date;
    short hour; ///< hour (0..23)
    short minute; ///< minute (0..59)
    short second; ///< second (0..59)
  };
};

#endif
