#include "_dataTypes.idl"

module ccReg {

  module Filters {  
    interface Base
    {
      readonly attribute string name;
      attribute boolean neg;
      /// Returns true, when attribute 'value' was set
      boolean isActive();
    };
    
    interface Iterator
    {
      exception INVALID {};
      void reset();
      void setNext();
      boolean hasNext();
      Base getFilter() raises (INVALID);
      void clearF();
    };

    interface Simple : Base
    {
    };
  
    interface Int : Simple
    {
      attribute short value;
    };

    interface IntInterval : Simple
    {
      attribute ccReg::IntInterval value;
    };

   // types encapsulating enums from Logging
    interface RequestServiceType : Simple
    {
      attribute ccReg::RequestServiceType value;
    };   

    interface RequestActionType : Simple
    {
      attribute ccReg::RequestActionType value;
    };

    interface Id : Simple
    {
      attribute TID value;
    };

    interface Bool : Simple
    {
      attribute boolean value;
    };

    interface Date : Simple
    {
      attribute DateInterval value;
    };

    interface DateTime : Simple
    {
      attribute DateTimeInterval value;
    };
  
    interface Str : Simple
    {
      attribute string value;
    };

    interface Compound : Base
    {
      Iterator getIterator();
    };

    interface Registrar : Compound
    {
      Id addId();
      Str addHandle();
      Str addName();
      Str addOrganization();
      Str addCity();
      Str addCountry();
    };

    interface ObjectState : Compound 
    {
      Id addStateId();
      DateTime addValidFrom();
      DateTime addValidTo();
    };

    interface Obj : Compound
    {
      Str addHandle();
      Str addAuthInfo();
      DateTime addCreateTime();
      DateTime addUpdateTime();
      DateTime addTransferTime();
      DateTime addDeleteTime();
      Registrar addCreateRegistrar();
      Registrar addUpdateRegistrar();
      Registrar addRegistrar();
      ObjectState addObjectState();
    };

    interface RequestProperty : Compound
    {
      Str addName();
    };

    interface RequestPropertyValue : Compound
    {
      Str addValue();
      Id  addRequestPropertyId();
      Bool addOutputFlag();
      RequestProperty addRequestProperty();
    };

    interface RequestData : Compound
    {
      Str addContent();
      Bool addResponseFlag();
    };

    interface Request : Compound
    {
      Id addId();
      DateTime addTimeBegin();
      DateTime addTimeEnd();
      Str addSourceIp();
      RequestServiceType addService();      
	/// TODO
      /// RequestActionType  addActionType();
      RequestData addRequestData();
      RequestPropertyValue addRequestPropertyValue();
    };

    interface Contact : Obj
    {
      Id addId();
      Str addName();
      Str addOrganization();
      Str addCity();
      Str addEmail();
      Str addNotifyEmail();
      Str addVat();
      Str addSsn();
    };
    
    interface NSSet : Obj
    {
      Id addId();
      Str addHostFQDN();
      Str addHostIP();
      Contact addTechContact();
    };

    interface KeySet : Obj
    {
        Id addId();
        Contact addTechContact();
    };

    interface Domain : Obj
    {
      Id addId();
      Date addExpirationDate();
      Date addOutZoneDate();
      Date addCancelDate();
      //Date addValidationExpirationDate();
      Contact addRegistrant();
      Contact addAdminContact();
      Contact addTempContact();
      NSSet addNSSet();
      KeySet addKeySet();
    };

    interface Action : Compound
    {
      Registrar addRegistrar();
      Int addType();
      Obj addObject();
      DateTime addTime();
      Str addClTRID();
      Str addSvTRID();
      Str addRequestHandle();
      Int addResponse();
      Int addEppCodeResponse();
    };

    interface Filter : Compound
    {
      Id addUserId(); // virtual filter (userid column will not be in result set)
      Id addGroupId();
      Int addType();
    };

    interface PublicRequest : Compound
    {
      Id addId();
      Int addType();
      Int addStatus();
      DateTime addCreateTime();
      DateTime addResolveTime();
      Str addReason();
      Str addEmailToAnswer();
      Object addObject();
      Action addEppAction();
    };

    interface File : Compound 
    {
      Id addId();
      Str addName();
      Str addPath();
      Str addMimeType();
      DateTime addCreateTime();
      Int addSize();
      Int addType();
    };

    interface Invoice : Compound
    {
      Id addZoneId();
      Int addType();
      Str addNumber();
      DateTime addCreateTime();
      Date addTaxDate();
      Registrar addRegistrar();
      Obj addObject();
      File addFile();
    };
    
    interface Mail : Compound
    {
      Id addId();
      Int addType();
      Str addHandle();
      DateTime addCreateTime();
      DateTime addModifyTime();
      Int addStatus();
      Int addAttempt();
      Str addMessage();
      File addAttachment();
    };

    interface Table
    {
      Compound add();
      void reload();
      void clear();
      Iterator getIterator();
      void loadFilter(in TID filterId);  //maybe move these two to Filters pagetable
      void saveFilter(in string name);
    };

  };

};
