#ifndef LOGGER_FILTER_IDL_
#define LOGGER_FILTER_IDL_


#include "_dataTypes.idl"

module Registry {
  interface PageTable;
};


module ccReg {
    interface LoggerFilter {
        exception OBJECT_NOT_FOUND {};

        struct Detail {
            ccReg::TID id;
            string timeBegin;
            string timeEnd;
            string    sourceIp;
            string service_type;
            string action_type;
            ccReg::TID session_id;
            string user_name;
            ccReg::TID user_id;
            boolean is_monitoring;
            string raw_request;
            string raw_response;
            long result_code;
            string result_name; 
            ccReg::RequestPropertiesDetail props;
            ccReg::ObjectReferences refs;
        };

        Registry::PageTable createPageTable(in string session_id);

        void deletePageTable(in string session_id);

        Detail getDetail(in TID id)
                      raises (OBJECT_NOT_FOUND);
    };
};

#endif
