module Registry 
{
    interface Messages 
    {
    
        //report a problem
        exception ErrorReport 
        {
            string reason;
        };
        
        void sendSms(
            in string contact_handle 
            ,in string phone
            ,in string content
            ,in string message_type
            ,in unsigned long contact_object_registry_id
            ,in unsigned long contact_history_historyid
        ) raises (ErrorReport);
    
	    struct PostalAddress 
	    {
	        string name;
	        string org;
	        string street1;
	        string street2;
	        string street3;
	        string city;
	        string state;
	        string code;
	        string county;
	    };
	    
	    typedef sequence<octet> ByteBuffer;
	    
	    void sendLetter(
	        in string contact_handle 
	        ,in PostalAddress address
	        ,in ByteBuffer file_content
	        ,in string file_name
	        ,in string file_type
	        ,in string message_type
            ,in unsigned long contact_object_registry_id
            ,in unsigned long contact_history_historyid
	    ) raises (ErrorReport);
    };
};