module Registry 
{
    interface Messages 
    {
    
        //report a problem
        exception ErrorReport 
        {
            string reason;
        };
        
        void sendSms(
            in string contact_handle 
            ,in string phone
            ,in string content
        ) raises (ErrorReport);
    
	    struct PostalAddress 
	    {
	        string name;
	        string org;
	        string street1;
	        string street2;
	        string street3;
	        string city;
	        string state;
	        string code;
	        string county;
	    };
	    
	    typedef sequence<octet> ByteBuffer;
	    
	    void sendLetter(
	        in string contact_handle 
	        ,in PostalAddress address
	        ,in ByteBuffer file_content
	        ,in string file_type
	    ) raises (ErrorReport);
    };
};