#ifndef PAIN_IDL_DB189D57EF894375BECB3931E4AD4E54
#define PAIN_IDL_DB189D57EF894375BECB3931E4AD4E54

module Registry {
module Pain {

exception OBJECT_NOT_FOUND {};
exception INVALID_VALUE {};
exception INTERNAL_SERVER_ERROR {};

typedef string Money;

interface PainIntf
{

    unsigned long long increase_credit_of_registrar(
            in string registrar_handle,
            in Money value)
    raises (OBJECT_NOT_FOUND, INVALID_VALUE, INTERNAL_SERVER_ERROR);

    unsigned long long decrease_credit_of_registrar(
            in string registrar_handle,
            in Money value)
    raises (OBJECT_NOT_FOUND, INVALID_VALUE, INTERNAL_SERVER_ERROR);

};

}; // Registry::Pain
}; // Registry

#endif
