// IDL interface for fred-server
#include "_dataTypes.idl"
#include "_Mailer.idl"
#include "Admin.idl"

#include "_EPP.idl"
#include "_TechCheck.idl"
#include "_FileManager.idl"
#include "Logger.idl"
